[package]
name = "aoc-scripts"
version = "0.1.0"
edition = "2021"

[workspace]

[[bin]]
name = "get-aoc-input"
path = "get-aoc-input.rs"

[dependencies]
clap = { version = "4.2", features = ["derive"] }
nom = "7.1.3"
reqwest = { version = "0.11.22", features = ["blocking"] }